---
title: "Discussion on End of Project Strategy"
author: "Collin Schwantes"
date: '`r Sys.Date()`'
output: 
  ehastyle::eha_avenir_pptx
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(officedown)
library(ggplot2)
library(rvg)
library(ehastyle)
```

## Introduction

-  Ending projects properly ensures compliance with award obligations, supports proper management of resources, and facilitates reuse of research outputs (code, data, protocols, etc). 
- Creating reusable research outputs increases research impact
- Primary beneficiary will be you. 

## Goals of today's discussion

- Provide an overview of planned strategy
- Understand where plan might break down
- Determine what training or infrastructure is needed


## Overview of strategy

- This strategy was developed off the archetypal EHA project
 that creates animal sampling (in Airtable) and human survey data (in ODK), and uses other data sets to inform statistical modeling done in R. 
- Decouple publication of results from release of data and code
- Over arching goal is to end projects with FAIR research outputs

## Overview of strategy: Guiding principles 

- Data management plans change with the project
- Digital and physical assets are properly managed
- Published outputs can be found and interpreted by users outside the project
   

## Overview of Strategy: Living data management plans

- The data management plan should serve as hub that records connections to different research outputs. 
- Data management plans should facilitate end of project activities.
  - Assets are described  
  - Roles and responsibilities are delineated
  - Standards and repositories are outlined

## Overview of Strategy: Asset Management

- Where possible, services that are no longer needed should be shut down
- Where possible, code running against cloud based data stores (airtable, odk, aws) should be run from version controlled data files. 
- User access to services should be reviewed 
- Physical items should be appropriately archived and documented (e.g. reagents, specimens, etc)
  
## Overview of Strategy: Code

- Use best practices for reproducible software
  - self contained projects (rstudio projects)
  - version controlled code (git and github)
  - literate coding practices (in line documentation)
  - dependency management (renv, docker)
  - automated code runs (targets, docker)
- Provide sufficient meta data about your project to give context and facilitate attribution

## Overview of Strategy: Data

- - Outputs should conform to a standard 
    - Default for data being frictionless data.
  - Outputs should should have project level and item level metadata
  - Outputs should contain or describe all necessary dependencies

## Mechanics of process

- Criteria for initiating close out process: 
What are the criteria for initiating the close out process? Do all projects need to do this? 
- What is the definition of done? 
- roles and responsibilities 

??? 


## Concrete Examples

We say we are going to do the following in a DMP, what do we need to make this a reality?

- Release version controlled reproducible code
- Deposit sero-survey data in Zenodo
- Deposit anonymized human survey data in Zenodo
- Publish nucleotide sequence data to Genbank
- Update data management plan with research outputs

## Discussion

- Accommodating schedules and approaches to when and how things are released - whats a reasonable timeline?
- How might we handle project extensions or second phases of a project?
- How should we close out assets? (airtable, aws, odk, etc.)
- Where do we need support for this work? Training, infrastructure?
- How might we handle data or assets that must remain private? 
