---
title: "Building Blocks of Reproducibility"
subtitle: "Part 2: Version control and collabortaion with GIT"
author: "Collin Schwantes"
date: "2022-06-14"
output:
  ehastyle::eha_avenir_xar
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      fig.height=5,
                      fig.align='center')
```

# Problem statement

Writing code for research purposes necessarily involves exploring data and analyses to gain understanding. It also often involves collaboration. In order for the outputs of collaboration and exploration to be reproducible, you need to have a system for 
organizing, versioning, and sharing your code.  


---
# Solution

Use a version control system that allows you to document specific changes in your code, collaborate effectively on code, and explore new ways of analyzing your data without generating new files or losing past work.

---
# Version control and collabortaion with GIT and Github

*GIT* - Distributed Version Control System - each collaborators computer becomes a code repository

*Github* - Collaboration platform and remote code repository 
  
???
To orgnanize, version, and share code we use Git and Github.


---
# To Review

1)  Use an IDE like Rstudio   
2)  Always start from a blank slate (save source not sessions)  
3)  Use projects and relative paths  
4)  Keep your code organized (avoid spaghetti code)  
5)  Leave yourself notes (literate programming) 

???


---
class: center, middle

#Thanks!