---
title: "Building Blocks of Reproducibility:"
subtitle: "`renv` - It works on my machine"
author: "Collin Schwantes"
date: "`r Sys.Date()`"
output:
  ehastyle::eha_avenir_xar
---

# Review from previous talks

**Reproducibility** is the ability to re-create results from the same data and code

1)  Use an IDE like Rstudio   
2)  Always start from a blank slate (save source not sessions)  
3)  Use projects and relative paths  
4)  Keep your code organized (avoid spaghetti code)  
5)  Leave yourself notes (literate programming)  
6)  Use a version control system  

???
In the context of reproducible research software, reproducibility is the ability to recreate results from the same code and data. 


---
class: center, middle
# But wait

How many packages do you use in your projects?

???

Those six principles would be sufficient if you were writing all the code in your project. 

---

# Problem

How do you create reproducible workflows when MOST of the code in your project comes from outside sources?

---

# Solution `renv`

- Simple and powerful package management system
-  Can be implemented quickly
- Allows you to create local project specific package libraries
- Allows you to share specific packages used with collaborators

---

# Things to keep in mind

`renv` does not fully capture your compute environment  
1. System libraries  
2. System dependencies  
3. R version  
4. Operating system
5. etc.

???

Renv is not a complete solution to reproducibility problems but it helps! A future session on containerizing code will help get us most of the way to fully capturing the compute environment for a project. 
---
# Basic `renv` workflow

- Create project in Rstudio
```
renv::init() #setup renv infrastructure in your project
```
- Work on code, install packages
``` 
renv::snapshot() # record the package versions at that point in time >> save
```
- What did I do?
```
renv::status() # check which packages have been added or modified
```

- Lockfile was updated or I've just pulled
the project down from Github
```
renv::restore() # restore packages from lock.file >> load
```
---

# What happens when on `renv::init()`?


| **File**            | **Usage**                                                                           |
| -----------------   | ----------------------------------------------------------------------------------- |
| `.Rprofile`         | *Used to activate `renv` for new R sessions launched in the project.                 |
| `renv.lock`         | *The lockfile, describing the state of your project's library at some point in time. |
| `renv/activate.R`   | The activation script run by the project `.Rprofile`.                               |
| `renv/library`      | The private project library.                                                        |
| `renv/settings.dcf` | *Project settings -- see `?settings` for more details.                               |

*files you will likely interact with

???

creates files and folders necessary to capture package dependencies.
---

# How do I collaborate with `renv`?

- Use git/github as version control - `renv` will ignore any package dependencies declared in files listed in `.gitignore` 
- The team figures out how you want to manage the `lock.file` 
- The project creator runs `renv::init()` and pushes the renv files to github
- Collaborators pull down files and use `renv::restore()` to install the specific  package versions on their machines and `renv::snapshot()` to update the `lock.file` then push changes to github

???

Renv plays very nicely with git and github - it will even ignore an packages listed in files in the .gitignore file. 

Before you start using renv on a large collaborative project, figure out how your team will manage the renv.lockfile and add that to your project readme/documentation. Generally speaking, the lockfile can be treated like any other git backed file. Making frequent and targeted commits and regular merges will help ensure the lockfiles between branches to become horribly out of sync. 

- From there its pretty straighforward- the project creator runs renv init and pushes the files up to github, and collaborators pull down those files, modify them, and push changes. 

---
# What if my collaborators use Windows? 

- They need to run `renv::equip()` to install necessary compiling tools (e.g. rtools) - this should handle most use cases
- If packages won't download properly modify the download methods
```{r eval=FALSE}
# in the console
usethis::edit_renviron() 
# in the .Renviron file set RENV_DOWNLOAD_METHOD - don't forget the trailing return
RENV_DOWNLOAD_METHOD = "libcurl" # or wininet

```
- If need be, you can setup a separate "windows" .Rprofile and use `renv::activate(profile = "windows")`

---

# Quick example

- create branch in [targets talk](https://github.com/ecohealthalliance/example_targets_bbr)
- `renv::init()`
- `renv::install("ecohealthalliance/airtabler")`
- `renv::snapshot()`
- git push
- `renv::history()`
- `renv::revert()`
- `renv::clean()`

---

# Where did we land?

1)  Use an IDE like Rstudio   
2)  Always start from a blank slate (save source not sessions)  
3)  Use projects and relative paths  
4)  Keep your code organized (avoid spaghetti code)  
5)  Leave yourself notes (literate programming)  
6)  Use a version control system  
7)  Use tools to capture your compute environment

???

Your code is potentially a small part of the code base that makes up your project. Capturing software dependencies will go a long ways towards making your code more reproducible. 

Renv is a good tool for recording R package versions. It has multiple levels of depth - from a "set it and forget" basic workflow to more granular package management specifications via settings and profiles. 

Using renv will largely prevent the common scenarios of "it runs on my machine" and "oh no! my old code won't run because of package versions" - you can and should start using it on all your projects. 


---

# Questions?

--- 

# Resources

- [`renv` Tutorials](https://rstudio.github.io/renv/articles/)
- [Noam's `renv` talk](https://airtable.com/appwlxIzmQx5njRtQ/tbledVCO9MRKkK9MW/viwfFq11zdwCbBT83/recFn7sg9rEiHC5gV?blocks=hide)
- [`renv` Talk from package Creator](https://www.youtube.com/watch?v=yjlEbIDevOs)
